#!/bin/sh

DIR=/tmp/node_exporter
DNSMASQ_ONE=$DIR/.dnsmasq.sed
PROMETHEUS_METRICS=$DIR/.prometheus.awk
DNSMASQ_PROM=$DIR/dnsmasq.prom
mkdir -p $DIR


cat > $DNSMASQ_ONE <<EOF
:loop
$!{
  /time/h
  n
  H
  /\n$/!b loop
}
g;p
EOF

cat > $PROMETHEUS_METRICS <<EOF
  function metric(name, labels, value) {
    if (labels == "")
      print name " " value
    else
      print name "{" labels "} " value
  }
  function gauge(name, value) {
    print "# TYPE " name " gauge"
  }
  function counter(name) {
    print "# TYPE " name " counter"
  }
  /cache size/ {  gauge("dnsmasq_cache_size");
                  metric("dnsmasq_cache_size", "", \$7+0)
                  split(\$8, stat, "/");
                  counter("dnsmasq_cache_free_live");
                  metric("dnsmasq_cache_free_live", "", stat[1]);
                  counter("dnsmasq_cache_insertions");
                  metric("dnsmasq_cache_insertions", "", stat[2]); }
  /queries forwarded/ { counter("dnsmasq_queries");
                        metric("dnsmasq_queries", "type=\"forward\"", \$7+0);
                        metric("dnsmasq_queries", "type=\"local_answer\"", \$11+0);
                   counter("dnsmasq_upstream_queries");
                   gauge("dnsmasq_upstream_latency"); }
  /queries sent/ { server="server=\"" substr(\$6,1,length(\$6)-1) "\"";
                   metric("dnsmasq_upstream_queries", server, \$9+0);
                   metric("dnsmasq_upstream_latency", server, \$19+0) }
EOF


killall -SIGUSR1 dnsmasq
tail -25 /tmp/syslog.log | grep dnsmasq | sed -n -e ':loop
$!{
  /time/h
  n
  H
  /\n$/!b loop
}
g;p'| awk -f $PROMETHEUS_METRICS > $DNSMASQ_PROM


echo "# TYPE dnsmasq_build_info gauge" >> $DNSMASQ_PROM
dnsmasq -vv | sed -n '1s/Dnsmasq version \([^ ]*\).*/dnsmasq_build_info{version="\1"} 1/p' >> $DNSMASQ_PROM

#Aug 13 19:00:00 dnsmasq[12191]: time 126796
#Aug 13 19:00:00 dnsmasq[12191]: cache size 1500, 0/61774 cache insertions re-used unexpired cache entries.
#Aug 13 19:00:00 dnsmasq[12191]: queries forwarded 29880, queries answered locally 38807
#Aug 13 19:00:00 dnsmasq[12191]: DNSSEC per-query subqueries HWM 0
#Aug 13 19:00:00 dnsmasq[12191]: DNSSEC per-query crypto work HWM 0
#Aug 13 19:00:00 dnsmasq[12191]: DNSSEC per-RRSet signature fails HWM 0
#Aug 13 19:00:00 dnsmasq[12191]: pool memory in use 0, max 352, allocated 2200
#Aug 13 19:00:00 dnsmasq[12191]: child processes for TCP requests: in use 0, highest since last SIGUSR1 0, max allowed 20.
#Aug 13 19:00:00 dnsmasq[12191]: server 76.76.2.40#53: queries sent 20568, retried 22, failed 299, nxdomain replies 1767, avg. latency 27ms
#Aug 13 19:00:00 dnsmasq[12191]: server 76.76.10.40#53: queries sent 14332, retried 36, failed 202, nxdomain replies 1214, avg. latency 26ms
