#!/bin/sh
swapon /tmp/mnt/san1/myswap.swp # Added by amtm

metrics_dir=/tmp/mnt/san2/metrics

# --no-collector.netdev.netlink
# https://github.com/prometheus/node_exporter/issues/2502
cd $metrics_dir/node_exporter
#nice ./node_exporter --collector.disable-defaults --collector.cpu --collector.filesystem --collector.loadavg --collector.meminfo --collector.netdev --no-collector.netdev.netlink --collector.stat --collector.time --collector.uname > /tmp/node_exporter.log 2>&1 &

cd $metrics_dir/prometheus
#nice ./prometheus --config.file=./prometheus.yml --enable-feature=agent --storage.agent.path=/tmp/prometheus.agent > /tmp/prometheus.log 2>&1 &

/jffs/opt/updateBlockList
