global:
  scrape_interval: 30s
  scrape_timeout:  10s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
#    - targets: ['localhost:9090']
    relabel_configs:
    - replacement: 'crater'
      target_label: instance

  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
    relabel_configs:
    - replacement: 'crater'
      target_label: instance

  - job_name: 'coredns'
    scrape_interval: 10m
    static_configs:
    - targets: ['crater.lan:9153']
    relabel_configs:
    - replacement: 'crater'
      target_label: instance

remote_write:
- url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: 67951
    password: eyJrIjoiNGFiYjBhZGFkZjc2NjIzZjI5Y2NlYTMyYzQ4Y2YxOTU2ZjkzOGU4YyIsIm4iOiJwcm9tZXRoZXVzIiwiaWQiOjQ3NjU2MH0=
  remote_timeout: 5s

