#!/bin/sh

export PATH=$PATH:/jffs/opt

ctrld.dns run -c /jffs/opt/ctrld.toml &

updateBlockList
service restart_dnsmasq

DIR=/tmp/node_exporter
mkdir -p $DIR

# --no-collector.netdev.netlink
# https://github.com/prometheus/node_exporter/issues/2502
nice node_exporter --collector.disable-defaults --collector.cpu --collector.filesystem --collector.loadavg --collector.meminfo --collector.netdev --no-collector.netdev.netlink --collector.stat --collector.textfile --collector.textfile.directory=$DIR --collector.time --collector.uname > $DIR/node_exporter.log 2>&1 &

cru a dnsmasq_exporter "*/5 * * * * /jffs/opt/dnsmasq_exporter"
cru a updateBlockList "0 3 * * Fri /jffs/opt/updateBlockList"

/jffs/scripts/YazFi startup & # YazFi
#/jffs/opt/ctrld.startup start

