#!/bin/sh

#cru a node_exporter "*/20 * * * * /opt/etc/init.d/S90node_exporter start"

export PATH=$PATH:/jffs/opt

DIR=/tmp/node_exporter
mkdir -p $DIR

# --no-collector.netdev.netlink
# https://github.com/prometheus/node_exporter/issues/2502
nice node_exporter --collector.disable-defaults --collector.cpu --collector.filesystem --collector.loadavg --collector.meminfo --collector.netdev --no-collector.netdev.netlink --collector.stat --collector.textfile --collector.textfile.directory=$DIR --collector.time --collector.uname > $DIR/node_exporter.log 2>&1 &

cru a dnsmasq_exporter "*/7 * * * * /jffs/opt/dnsmasq_exporter"
