#!/bin/sh

/jffs/scripts/sbnMerlin run-config & # (sbnMerlin) Network Isolation Tool
sleep 5
cru d sbnMerlin.1
cru d sbnMerlin.2

export PATH=$PATH:/jffs/opt

DIR=/tmp/node_exporter
mkdir -p $DIR

# --no-collector.netdev.netlink
# https://github.com/prometheus/node_exporter/issues/2502
nice node_exporter --collector.disable-defaults --collector.cpu --collector.filesystem --collector.loadavg --collector.meminfo --collector.netdev --no-collector.netdev.netlink --collector.stat --collector.textfile --collector.textfile.directory=$DIR --collector.time --collector.uname > $DIR/node_exporter.log 2>&1 &

cru a dnsmasq_exporter "*/5 * * * * /jffs/opt/dnsmasq_exporter"
cru a updateBlockList "0 3 * * Fri /jffs/opt/updateBlockList"
cru a mod_temp "* * * * * /jffs/opt/mod_temp"

#ctrld.dns run -c /jffs/opt/ctrld.toml &
#blocky.startup

/jffs/opt/updateBlockList
