#! /bin/sh

DNSMASQ_DIR=/tmp/dnsmasq.d

mkdir -p $DNSMASQ_DIR

cd $DNSMASQ_DIR

#wget -O $DNSMASQ_DIR/multi.conf https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/multi.txt
wget -O $DNSMASQ_DIR/pro.conf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/dnsmasq/pro.txt

service restart_dnsmasq
