#!/bin/sh
ENABLED="yes"
WORK_DIR="/tmp/agh"
YAML_DIR="/opt/etc/AdGuardHome"
PID_FILE="/opt/var/run/AdGuardHome.pid"
PROCS="AdGuardHome"
ARGS="-s run -c ${YAML_DIR}/AdGuardHome.yaml -w $WORK_DIR --pidfile $PID_FILE --no-check-update -l syslog"
PREARGS="env TZ=/etc/localtime"
PRECMD="killall -9 dnsmasq"
POSTCMD="service restart_dnsmasq"
DESC="$PROCS"
PATH="/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TZ="$(cat /etc/TZ)"

[ -d "$WORK_DIR" ] || mkdir -m 0755 -p "$WORK_DIR"

[ -z "$SCRIPT_LOC" ] && . /jffs/addons/AdGuardHome.d/AdGuardHome.sh
